
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module part1(

	output [7:0]
		sum, 
	output 
		overflow,
	input 
		carryIn, 
	input [7:0]
		a,
		b
	 

);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [7:0] carry;




//=======================================================
//  Structural coding
//=======================================================
FullAdder RCAdder0 ( carry[0], sum[0], a[0], b[0], carryIn);

FullAdder RCAdder1 ( carry[1], sum[1], a[1], b[1], carry[0]);

FullAdder RCAdder2 ( carry[2], sum[2], a[2], b[2], carry[1]);

FullAdder RCAdder3 ( carry[3], sum[3], a[3], b[3], carry[2]);

FullAdder RCAdder4 ( carry[4], sum[4], a[4], b[4], carry[3]);

FullAdder RCAdder5 ( carry[5], sum[5], a[5], b[5], carry[4]);

FullAdder RCAdder6 ( carry[6], sum[6], a[6], b[6], carry[5]);

FullAdder RCAdder7 ( carry[7], sum[7], a[7], b[7], carry[6]);


assign overflow = carry[6] ^ carry[7];








endmodule
